### ISSUE TITLE
Suggestion: Return possible exposure range after setting framerate 

### ISSUE THREAD

**Issue by ianshmean** [samuelpowell/Spinnaker.jl#21]
i.e. return exposure range from `framerate!()`

It would help for setting interactive controls (sliders etc) or just doing limit checks

**Comment by samuelpowell** [comment]
I understand the motivation, but I don't think this is a good idea because:
 - many other functions change the range, or the availability of other options, and I don't think that we could try and return everything that now has different options. For example, should changing the exposure mode to trigger width return information regarding the fact that the exposure time is now disabled (or has no effect)?
- the value set on the camera doesn't always match the requested value, and it is important to return the actual set value to the user

As you know most of the current functions in this package are very lightweight wrappers over the underlying node functionality, and this is intentional. I think what you are describing is a higher level interface designed by someone (such as yourself) who understands all the implications of each of the settings. I think what you are describing is a new interface which implements a defined mode, e.g., an interface which says "I care about frame rate: what settings are now available to me, and what is their range, give me an easy way to set them". Some care would be required to design these in an extensible way.

**Comment by ianshmean** [comment]
Fair point. Good to keep them separated.

There are some missing range functions that would be helpful for GUI controls. I can look into them if you don't get there first:
- framerateLimits() -> (Float,Float)
- exposureLimits() -> (Float,Float)
- gainLimits() -> (Float,Float)
- blackLevelLimits() -> (Float,Float)
- gammaLimits() -> (Float,Float)
- offsetXLimits() -> (Int,Int)
- offsetYLimits() -> (Int,Int)

These are needed as well as sensordims() because there seems to be a min limit too:
- imageWidthLimits() -> (Int,Int)  
- imageHeightLimits() -> (Int,Int)

**Comment by samuelpowell** [comment]
@ianshmean PR inbound.

**Comment by samuelpowell** [comment]
Ref #22
